"""add onboarding_payments

Revision ID: a5c0cc710db5
Revises: f2cd2cbd583c
Create Date: 2026-03-03 12:54:01.099476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c0cc710db5'
down_revision = 'f2cd2cbd583c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('amount_kes', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('rejected_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['rejected_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_payments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_payments_confirmed_by_admin_id'), ['confirmed_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_payments_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_payments_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_payments_rejected_by_admin_id'), ['rejected_by_admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_payments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onboarding_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_payments_status'))
        batch_op.drop_index(batch_op.f('ix_onboarding_payments_rejected_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_onboarding_payments_created_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_payments_confirmed_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_payments_client_id'))

    op.drop_table('onboarding_payments')
    # ### end Alembic commands ###
